// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[Keyless]
public partial class QryAprovados
{
    [Column("ordem")]
    public float? Ordem { get; set; }

    [Column("ordem_sigla_serv")]
    public float? OrdemSiglaServ { get; set; }

    [Column("nivel")]
    public int? Nivel { get; set; }

    [Column("data_aprovado")]
    public DateTime? DataAprovado { get; set; }

    [Column("data_de_expedicao")]
    public DateOnly? DataDeExpedicao { get; set; }

    [Column("meta_producao")]
    public DateTime? MetaProducao { get; set; }

    [Column("sigla")]
    [StringLength(20)]
    public string Sigla { get; set; }

    [Column("sigla_serv")]
    [StringLength(20)]
    public string SiglaServ { get; set; }

    [Column("nome")]
    [StringLength(150)]
    public string Nome { get; set; }

    [Column("tema")]
    [StringLength(150)]
    public string Tema { get; set; }

    [Column("obs_especial")]
    [StringLength(200)]
    public string ObsEspecial { get; set; }

    [Column("resp_cliente", TypeName = "character varying")]
    public string RespCliente { get; set; }

    [Column("est")]
    [StringLength(20)]
    public string Est { get; set; }

    [Column("cidade")]
    [StringLength(50)]
    public string Cidade { get; set; }

    [Column("memo_resp")]
    [StringLength(30)]
    public string MemoResp { get; set; }

    [Column("memo_data")]
    public DateOnly? MemoData { get; set; }

    [Column("chk_resp")]
    [StringLength(30)]
    public string ChkResp { get; set; }

    [Column("chk_data")]
    public DateOnly? ChkData { get; set; }

    [Column("cronog_data")]
    public DateTime? CronogData { get; set; }

    [Column("cronog_resp")]
    [StringLength(30)]
    public string CronogResp { get; set; }

    [Column("as_built_plantas")]
    [StringLength(30)]
    public string AsBuiltPlantas { get; set; }

    [Column("as_built_plantas_data")]
    public DateTime? AsBuiltPlantasData { get; set; }

    [Column("rel_inflamabilidade")]
    [StringLength(30)]
    public string RelInflamabilidade { get; set; }

    [Column("data_rel_inflamabilidade")]
    public DateOnly? DataRelInflamabilidade { get; set; }

    [Column("meta_rel_inflamabilidade")]
    public DateOnly? MetaRelInflamabilidade { get; set; }

    [Column("pa")]
    [StringLength(50)]
    public string Pa { get; set; }

    [Column("mlamp_led")]
    [StringLength(50)]
    public string MlampLed { get; set; }

    [Column("obs_iluminacao")]
    [StringLength(50)]
    public string ObsIluminacao { get; set; }

    [Column("resp_memo_visual")]
    [StringLength(30)]
    public string RespMemoVisual { get; set; }

    [Column("data_memo_visual")]
    public DateOnly? DataMemoVisual { get; set; }

    [Column("resp_cenas")]
    [StringLength(50)]
    public string RespCenas { get; set; }

    [Column("resp_trilha")]
    [StringLength(30)]
    public string RespTrilha { get; set; }

    [Column("data_reuniao_conceito")]
    public DateOnly? DataReuniaoConceito { get; set; }

    [Column("resp_planta_pca")]
    [StringLength(30)]
    public string RespPlantaPca { get; set; }

    [Column("prazo_planta_pca")]
    public DateOnly? PrazoPlantaPca { get; set; }

    [Column("conclusao_planta_pca")]
    public DateOnly? ConclusaoPlantaPca { get; set; }

    [Column("resp_revisao_planta")]
    [StringLength(30)]
    public string RespRevisaoPlanta { get; set; }

    [Column("data_revisao_planta")]
    public DateOnly? DataRevisaoPlanta { get; set; }

    [Column("obs_revisao")]
    [StringLength(150)]
    public string ObsRevisao { get; set; }

    [Column("ok_planta_pca")]
    public bool? OkPlantaPca { get; set; }

    [Column("planta_pca")]
    [StringLength(30)]
    public string PlantaPca { get; set; }

    [Column("liberacao_planta_pca")]
    public DateTime? LiberacaoPlantaPca { get; set; }

    [Column("resp_planta_mall")]
    [StringLength(30)]
    public string RespPlantaMall { get; set; }

    [Column("prazo_planta_mall")]
    public DateOnly? PrazoPlantaMall { get; set; }

    [Column("ok_planta_mall")]
    public bool? OkPlantaMall { get; set; }

    [Column("planta_mall")]
    [StringLength(30)]
    public string PlantaMall { get; set; }

    [Column("conclusao_planta_mall")]
    public DateTime? ConclusaoPlantaMall { get; set; }

    [Column("laco")]
    [StringLength(30)]
    public string Laco { get; set; }

    [Column("acabamento_construcao")]
    public string AcabamentoConstrucao { get; set; }

    [Column("acabamento_fibra")]
    public string AcabamentoFibra { get; set; }

    [Column("acabamento_moveis")]
    public string AcabamentoMoveis { get; set; }

    [Column("rede")]
    [StringLength(30)]
    public string Rede { get; set; }

    [Column("memorial_visual_liberado_por")]
    [StringLength(30)]
    public string MemorialVisualLiberadoPor { get; set; }

    [Column("memorial_visual_liberado_em")]
    public DateOnly? MemorialVisualLiberadoEm { get; set; }

    [Column("somadecubagem_total")]
    public double? SomadecubagemTotal { get; set; }

    [Column("tipo_evento")]
    [StringLength(30)]
    public string TipoEvento { get; set; }

    [Column("divi_caminhao")]
    public string DiviCaminhao { get; set; }

    [Column("resp_planta_fachada")]
    [StringLength(30)]
    public string RespPlantaFachada { get; set; }

    [Column("prazo_planta_fachada")]
    public DateOnly? PrazoPlantaFachada { get; set; }

    [Column("ok_planta_fachada")]
    public bool? OkPlantaFachada { get; set; }

    [Column("planta_fachada")]
    [StringLength(30)]
    public string PlantaFachada { get; set; }

    [Column("conclusao_planta_fachada")]
    public DateTime? ConclusaoPlantaFachada { get; set; }

    [Column("resp_estruturas")]
    [StringLength(50)]
    public string RespEstruturas { get; set; }

    [Column("projeto_novo")]
    [StringLength(5)]
    public string ProjetoNovo { get; set; }

    [Column("id_aprovado")]
    public int? IdAprovado { get; set; }

    [Column("cor_predominante")]
    [StringLength(100)]
    public string CorPredominante { get; set; }

    [Column("resp_planta_base")]
    [StringLength(50)]
    public string RespPlantaBase { get; set; }

    [Column("prazo_planta_base")]
    public DateOnly? PrazoPlantaBase { get; set; }

    [Column("conclusao_planta_base")]
    public DateOnly? ConclusaoPlantaBase { get; set; }

    [Column("resp_revisao_planta_base")]
    [StringLength(50)]
    public string RespRevisaoPlantaBase { get; set; }

    [Column("data_revisao_planta_base")]
    public DateOnly? DataRevisaoPlantaBase { get; set; }

    [Column("ok_planta_base")]
    public bool? OkPlantaBase { get; set; }

    [Column("planta_base")]
    [StringLength(50)]
    public string PlantaBase { get; set; }

    [Column("liberacao_planta_base")]
    public DateTime? LiberacaoPlantaBase { get; set; }

    [Column("resp_revisao_comite")]
    [StringLength(50)]
    public string RespRevisaoComite { get; set; }

    [Column("data_revisao_comite")]
    public DateOnly? DataRevisaoComite { get; set; }

    [Column("revisao_custo")]
    [StringLength(5)]
    public string RevisaoCusto { get; set; }
}