// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[Keyless]
public partial class QryEnderecamentoGalpao
{
    [Column("id_endereco")]
    public int? IdEndereco { get; set; }

    [Column("endereco")]
    [StringLength(30)]
    public string Endereco { get; set; }

    [Column("barcode")]
    [StringLength(15)]
    public string Barcode { get; set; }
}