// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[Keyless]
public partial class QryLookup
{
    [Column("sigla_serv")]
    [StringLength(15)]
    public string SiglaServ { get; set; }

    [Column("baia_caminhao", TypeName = "character varying")]
    public string BaiaCaminhao { get; set; }

    [Column("barcode")]
    [StringLength(15)]
    public string Barcode { get; set; }

    [Column("qrcode")]
    public string Qrcode { get; set; }
}