// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[Table("tbl_controle_caixa_setor", Schema = "expedicao")]
public partial class TblControleCaixaSetor
{
    [Column("barcode")]
    [StringLength(20)]
    public string Barcode { get; set; }

    [Column("cadastradopor")]
    [StringLength(30)]
    public string Cadastradopor { get; set; }

    [Column("cadastrado_em")]
    public DateTime? CadastradoEm { get; set; }

    [Key]
    [Column("cod_linha_caixa_setor")]
    public int CodLinhaCaixaSetor { get; set; }

    [Column("cod_setor")]
    public int? CodSetor { get; set; }

    [Column("localizacao")]
    [StringLength(10)]
    public string Localizacao { get; set; }

    [Column("galpao")]
    [StringLength(10)]
    public string Galpao { get; set; }
}