// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[Table("tbl_historico_cubagem_ponderada", Schema = "expedicao")]
[Index("Sigla", "Ano", Name = "tbl_historico_cubagem_ponderada_sigla_ano_key", IsUnique = true)]
public partial class TblHistoricoCubagemPonderada
{
    [Column("ordem")]
    [StringLength(10)]
    public string Ordem { get; set; }

    [Column("tipo_fecha")]
    [StringLength(30)]
    public string TipoFecha { get; set; }

    [Column("ano")]
    public int Ano { get; set; }

    [Column("sigla")]
    [StringLength(30)]
    public string Sigla { get; set; }

    [Column("data_fecha")]
    public DateOnly? DataFecha { get; set; }

    [Column("cubagem_ponderada")]
    public double? CubagemPonderada { get; set; }

    [Column("tema")]
    [StringLength(150)]
    public string Tema { get; set; }

    [Column("tema_novo_remodelado")]
    [StringLength(10)]
    public string TemaNovoRemodelado { get; set; }

    [Key]
    [Column("id_linha_ponderada")]
    public int IdLinhaPonderada { get; set; }
}