// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[Table("tbl_movimentacao_volume_shopping", Schema = "expedicao")]
public partial class TblMovimentacaoVolumeShopping
{
    [Key]
    [Column("id_linha_inserida")]
    public int IdLinhaInserida { get; set; }

    [Column("barcode_volume")]
    [StringLength(15)]
    public string BarcodeVolume { get; set; }

    [Column("barcode_endereco")]
    [StringLength(15)]
    public string BarcodeEndereco { get; set; }

    [Column("inserido_por")]
    [StringLength(100)]
    public string InseridoPor { get; set; }

    [Column("inserido_em")]
    public DateTime? InseridoEm { get; set; }
}