// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[Table("tbl_media_cubagem_produto", Schema = "expedicao")]
public partial class TblMediaCubagemProduto
{
    [Key]
    [Column("codcompladicional")]
    public int Codcompladicional { get; set; }

    [Column("m3")]
    public double? M3 { get; set; }

    [Column("pl")]
    public double? Pl { get; set; }

    [Column("pb")]
    public double? Pb { get; set; }
}