// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[PrimaryKey("Sigla", "Codcompladicional", "DetalheReqCompl", "Origem")]
[Table("tbl_materiais_controlados_retorno", Schema = "expedicao")]
public partial class TblMateriaisControladosRetorno
{
    [Required]
    [Column("cliente")]
    [StringLength(20)]
    public string Cliente { get; set; }

    [Key]
    [Column("sigla")]
    [StringLength(20)]
    public string Sigla { get; set; }

    [Column("planilha")]
    [StringLength(100)]
    public string Planilha { get; set; }

    [Column("descricao")]
    [StringLength(254)]
    public string Descricao { get; set; }

    [Column("unidade")]
    [StringLength(5)]
    public string Unidade { get; set; }

    [Key]
    [Column("codcompladicional")]
    public int Codcompladicional { get; set; }

    [Column("inventario_shop")]
    public float? InventarioShop { get; set; }

    [Column("qtde")]
    public float? Qtde { get; set; }

    [Column("qtde_retorno")]
    public float? QtdeRetorno { get; set; }

    [Column("saldo_retorno")]
    public float? SaldoRetorno { get; set; }

    [Column("digitado_por")]
    [StringLength(30)]
    public string DigitadoPor { get; set; }

    [Column("digitado_em", TypeName = "timestamp without time zone")]
    public DateTime? DigitadoEm { get; set; }

    [Column("invent_shopp_desmont")]
    public float? InventShoppDesmont { get; set; }

    [Key]
    [Column("detalhe_req_compl")]
    public int DetalheReqCompl { get; set; }

    [Key]
    [Column("origem")]
    [StringLength(1)]
    public string Origem { get; set; }
}