// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[PrimaryKey("Sigla", "Nome")]
[Table("tbl_resp_controlado", Schema = "expedicao")]
public partial class TblRespControlado
{
    [Key]
    [Column("sigla")]
    [StringLength(40)]
    public string Sigla { get; set; }

    [Key]
    [Column("nome")]
    [StringLength(150)]
    public string Nome { get; set; }
}