// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[Table("tbl_retorno_cliente", Schema = "expedicao")]
public partial class TblRetornoCliente
{
    [Column("quantidade")]
    public double? Quantidade { get; set; }

    [Column("inserido_por")]
    [StringLength(30)]
    public string InseridoPor { get; set; }

    [Column("inserido_em", TypeName = "timestamp without time zone")]
    public DateTime? InseridoEm { get; set; }

    [Column("id_aprovado")]
    public int IdAprovado { get; set; }

    [Column("codcompladicional")]
    public int Codcompladicional { get; set; }

    [Key]
    [Column("retorno_cliente_id")]
    public int RetornoClienteId { get; set; }
}