// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[Table("t_caixas_tabjac", Schema = "expedicao")]
[Index("NomeCaixa", Name = "t_caixas_tabjac_nome_caixa_key", IsUnique = true)]
public partial class TCaixasTabjac
{
    [Key]
    [Column("cod_caixa")]
    public int CodCaixa { get; set; }

    [Column("nome_caixa")]
    [StringLength(20)]
    public string NomeCaixa { get; set; }

    [Column("setor")]
    [StringLength(30)]
    public string Setor { get; set; }

    [Column("impresso")]
    [StringLength(5)]
    public string Impresso { get; set; }

    [Column("sequencia")]
    public int? Sequencia { get; set; }

    [Column("inserido_por")]
    [StringLength(30)]
    public string InseridoPor { get; set; }

    [Column("inserido_em", TypeName = "timestamp without time zone")]
    public DateTime? InseridoEm { get; set; }
}