// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[Table("t_conf_carga_geral", Schema = "expedicao")]
public partial class TConfCargaGeral
{
    [Key]
    [Column("barcode")]
    [StringLength(16)]
    public string Barcode { get; set; }

    [Column("doca_origem")]
    [StringLength(50)]
    public string DocaOrigem { get; set; }

    [Column("data")]
    public DateOnly? Data { get; set; }

    [Column("shopp")]
    [StringLength(20)]
    public string Shopp { get; set; }

    [Column("resp")]
    [StringLength(20)]
    public string Resp { get; set; }

    [Column("caminhao")]
    [StringLength(10)]
    public string Caminhao { get; set; }

    [Column("entradasistema")]
    public DateTime? Entradasistema { get; set; }

    [Column("alterado_por")]
    [StringLength(30)]
    public string AlteradoPor { get; set; }

    [Column("data_altera")]
    public DateTime? DataAltera { get; set; }

    [Column("inserido_por")]
    [StringLength(30)]
    public string InseridoPor { get; set; }

    [Column("inserido_em", TypeName = "timestamp without time zone")]
    public DateTime? InseridoEm { get; set; }
}