// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[Table("t_confirma_baia_local", Schema = "expedicao")]
public partial class TConfirmaBaiaLocal
{
    [Key]
    [Column("barcode")]
    [StringLength(16)]
    public string Barcode { get; set; }

    [Column("data")]
    public DateTime? Data { get; set; }

    [Column("resp")]
    [StringLength(20)]
    public string Resp { get; set; }

    [Column("local")]
    [StringLength(20)]
    public string Local { get; set; }

    [Column("inserido_por")]
    [StringLength(30)]
    public string InseridoPor { get; set; }

    [Column("inserido_em", TypeName = "timestamp without time zone")]
    public DateTime? InseridoEm { get; set; }
}