// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[Table("t_controle_baia_local", Schema = "expedicao")]
public partial class TControleBaiaLocal
{
    [Key]
    [Column("sigla")]
    [StringLength(20)]
    public string Sigla { get; set; }

    [Required]
    [Column("baia_local")]
    [StringLength(20)]
    public string BaiaLocal { get; set; }

    [Column("inserido_por")]
    [StringLength(30)]
    public string InseridoPor { get; set; }

    [Column("inserido_em", TypeName = "timestamp without time zone")]
    public DateTime? InseridoEm { get; set; }
}