// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[Table("t_controle_baia", Schema = "expedicao")]
public partial class TControleBaia
{
    [Key]
    [Column("barcode")]
    [StringLength(16)]
    public string Barcode { get; set; }

    [Column("data")]
    public DateTime Data { get; set; }

    [Required]
    [Column("sigla")]
    [StringLength(20)]
    public string Sigla { get; set; }

    [Required]
    [Column("incluido_por")]
    [StringLength(20)]
    public string IncluidoPor { get; set; }

    [Column("inserido_por")]
    [StringLength(30)]
    public string InseridoPor { get; set; }

    [Column("inserido_em", TypeName = "timestamp without time zone")]
    public DateTime? InseridoEm { get; set; }
}