// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[Table("t_conferentes", Schema = "expedicao")]
[Index("Nome", "Local", Name = "t_conferentes_nome_local_key", IsUnique = true)]
public partial class TConferentes
{
    [Column("nome")]
    [StringLength(50)]
    public string Nome { get; set; }

    [Column("local")]
    [StringLength(10)]
    public string Local { get; set; }

    [Key]
    [Column("id_conferente")]
    public int IdConferente { get; set; }
}