// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

/// <summary>
/// Transferencia shooping
/// </summary>
[Table("t_envio_baia_galpoes_tab", Schema = "expedicao")]
public partial class TEnvioBaiaGalpoesTab
{
    [Key]
    [Column("barcode")]
    [StringLength(16)]
    public string Barcode { get; set; }

    [Column("data_envio")]
    public DateOnly? DataEnvio { get; set; }

    [Column("shopp")]
    [StringLength(10)]
    public string Shopp { get; set; }

    [Column("resp")]
    [StringLength(20)]
    public string Resp { get; set; }

    [Column("caminhao")]
    [StringLength(10)]
    public string Caminhao { get; set; }

    [Column("baia_destino")]
    [StringLength(10)]
    public string BaiaDestino { get; set; }

    [Column("enviado")]
    [StringLength(5)]
    public string Enviado { get; set; }

    [Column("inserido_por")]
    [StringLength(30)]
    public string InseridoPor { get; set; }

    [Column("inserido_em", TypeName = "timestamp without time zone")]
    public DateTime? InseridoEm { get; set; }
}