// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[Table("t_exped", Schema = "expedicao")]
public partial class TExped
{
    [Key]
    [Column("codexped")]
    public int Codexped { get; set; }

    [Column("qtd_expedida")]
    public double? QtdExpedida { get; set; }

    [Column("vol_exp")]
    public int? VolExp { get; set; }

    [Column("vol_tot_exp")]
    public int? VolTotExp { get; set; }

    [Column("pl")]
    public float? Pl { get; set; }

    [Column("pb")]
    public float? Pb { get; set; }

    [Column("largura")]
    public float? Largura { get; set; }

    [Column("altura")]
    public float? Altura { get; set; }

    [Column("profundidade")]
    public float? Profundidade { get; set; }

    [Column("codvol")]
    [StringLength(40)]
    public string Codvol { get; set; }

    [Column("cadastrado_por")]
    [StringLength(20)]
    public string CadastradoPor { get; set; }

    [Column("quando")]
    public DateTime? Quando { get; set; }

    [Column("baia_virtual")]
    [StringLength(5)]
    public string BaiaVirtual { get; set; }

    [Column("modelo_de_cx")]
    [StringLength(20)]
    public string ModeloDeCx { get; set; }

    [Column("coddetalhescompl")]
    public int Coddetalhescompl { get; set; }

    [Column("alterado_por")]
    [StringLength(20)]
    public string AlteradoPor { get; set; }

    [Column("alterado_quando", TypeName = "timestamp without time zone")]
    public DateTime? AlteradoQuando { get; set; }

    [Column("inserido_por")]
    [StringLength(30)]
    public string InseridoPor { get; set; }

    [Column("inserido_em", TypeName = "timestamp without time zone")]
    public DateTime? InseridoEm { get; set; }

    [Column("operacao")]
    [StringLength(50)]
    public string Operacao { get; set; }

    [Column("volume")]
    public int? Volume { get; set; }

    [Column("nf_emitida")]
    public bool? NfEmitida { get; set; }

    public virtual TCaixas CodvolNavigation { get; set; }
}