// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[Table("t_romaneio", Schema = "expedicao")]
public partial class TRomaneio
{
    [Key]
    [Column("cod_romaneiro")]
    public int CodRomaneiro { get; set; }

    [Column("data_carregamento")]
    public DateOnly DataCarregamento { get; set; }

    [Column("hora_chegada")]
    public TimeOnly HoraChegada { get; set; }

    [Column("codtransportadora")]
    public int Codtransportadora { get; set; }

    [Required]
    [Column("nome_motorista")]
    [StringLength(50)]
    public string NomeMotorista { get; set; }

    [Required]
    [Column("placa_caminhao")]
    [StringLength(8)]
    public string PlacaCaminhao { get; set; }

    [Required]
    [Column("placa_cidade")]
    [StringLength(60)]
    public string PlacaCidade { get; set; }

    [Required]
    [Column("placa_estado")]
    [StringLength(2)]
    public string PlacaEstado { get; set; }

    [Required]
    [Column("placa_carroceria")]
    [StringLength(8)]
    public string PlacaCarroceria { get; set; }

    [Required]
    [Column("placa_carroceria_cidade")]
    [StringLength(60)]
    public string PlacaCarroceriaCidade { get; set; }

    [Required]
    [Column("placa_carroceria_estado")]
    [StringLength(2)]
    public string PlacaCarroceriaEstado { get; set; }

    [Column("numero_container")]
    [StringLength(10)]
    public string NumeroContainer { get; set; }

    [Column("bau_altura")]
    public double? BauAltura { get; set; }

    [Column("bau_largura")]
    public double? BauLargura { get; set; }

    [Column("bau_profundidade")]
    public double? BauProfundidade { get; set; }

    [Column("m3_carregado")]
    public double? M3Carregado { get; set; }

    [Column("bau_soba")]
    public double? BauSoba { get; set; }

    [Column("condicao_caminhao")]
    [StringLength(15)]
    public string CondicaoCaminhao { get; set; }

    [Column("inicio_carregamento")]
    public TimeOnly? InicioCarregamento { get; set; }

    [Column("termino_carregamento")]
    public TimeOnly? TerminoCarregamento { get; set; }

    [Column("numero_caminhao")]
    public int? NumeroCaminhao { get; set; }

    [Required]
    [Column("shopping_destino")]
    [StringLength(20)]
    public string ShoppingDestino { get; set; }

    [Column("local_carregamento")]
    [StringLength(10)]
    public string LocalCarregamento { get; set; }

    [Column("num_lacres")]
    [StringLength(35)]
    public string NumLacres { get; set; }

    [Column("nome_conferente")]
    [StringLength(30)]
    public string NomeConferente { get; set; }

    [Column("incluido_por")]
    [StringLength(30)]
    public string IncluidoPor { get; set; }

    [Column("incluido_data", TypeName = "timestamp without time zone")]
    public DateTime? IncluidoData { get; set; }

    [Column("alterado_por")]
    [StringLength(30)]
    public string AlteradoPor { get; set; }

    [Column("alterado_data", TypeName = "timestamp without time zone")]
    public DateTime? AlteradoData { get; set; }

    [Required]
    [Column("numero_cnh")]
    [StringLength(12)]
    public string NumeroCnh { get; set; }

    [Column("telefone_motorista")]
    [StringLength(30)]
    public string TelefoneMotorista { get; set; }

    [Column("m3_portaria")]
    public float? M3Portaria { get; set; }

    [Column("operacao")]
    [StringLength(30)]
    public string Operacao { get; set; }

    [Column("conferente_descarregamento")]
    [StringLength(30)]
    public string ConferenteDescarregamento { get; set; }

    [Column("lacre_chegada")]
    [StringLength(50)]
    public string LacreChegada { get; set; }

    [Column("hora_inicio_descarregamento")]
    public TimeOnly? HoraInicioDescarregamento { get; set; }

    [Column("hora_termino_descarregamento")]
    public TimeOnly? HoraTerminoDescarregamento { get; set; }

    [Column("data_inicio_descarregamento")]
    public DateOnly? DataInicioDescarregamento { get; set; }

    [Column("data_termino_descarregamento")]
    public DateOnly? DataTerminoDescarregamento { get; set; }

    [Column("data_saida_caminhao")]
    public DateOnly? DataSaidaCaminhao { get; set; }

    [Column("hora_saida_caminhao")]
    public TimeOnly? HoraSaidaCaminhao { get; set; }

    [Column("data_hora_liberacao", TypeName = "timestamp without time zone")]
    public DateTime? DataHoraLiberacao { get; set; }
}