// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[Table("t_transf_lookup_confere_tab", Schema = "expedicao")]
public partial class TTransfLookupConfereTab
{
    [Key]
    [Column("barcode")]
    [StringLength(16)]
    public string Barcode { get; set; }
}